#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER


int check1 = 0;
int check2 = 0;

int isbutton1()
{
      bsp_io_level_t lev1, lev2;

      R_IOPORT_PinRead(&g_ioport_ctrl, button1, &lev1);
      R_BSP_SoftwareDelay (30, BSP_DELAY_UNITS_MILLISECONDS);
      R_IOPORT_PinRead(&g_ioport_ctrl, button1, &lev2);

      if(lev1 == 0 && lev2 == 0)return 0;
      else return 1;

}

int isbutton2(){


    bsp_io_level_t lev1, lev2;

    R_IOPORT_PinRead(&g_ioport_ctrl, button2, &lev1);
    R_BSP_SoftwareDelay (30, BSP_DELAY_UNITS_MILLISECONDS);
    R_IOPORT_PinRead(&g_ioport_ctrl, button2, &lev2);

    if(lev1 == 0 && lev2 == 0)return 0;
    else return 1;


}

int ledarr[4] = {0,};
bsp_io_port_pin_t str[4]= {LED6, LED5, LED4, LED3};

int paht[5] = {0,};

void DFS_r(int x, int size, int count)
{


    if(isbutton2() == 0)
    {
        R_BSP_SoftwareDelay (20, BSP_DELAY_UNITS_MILLISECONDS);
        while(1)
        {
            if(isbutton2() == 0)
                break;
        }
    }

    if(isbutton1() == 0)
           check1 = 1;

     if(check1 == 1)return;


    if (count == size)
    {
        for(int i  = 0; i < 4; i++){
            R_IOPORT_PinWrite(&g_ioport_ctrl, str[i], paht[i]);
        }

         R_BSP_SoftwareDelay (300, BSP_DELAY_UNITS_MILLISECONDS);

        if(isbutton2() == 0)
         {
               R_BSP_SoftwareDelay (20, BSP_DELAY_UNITS_MILLISECONDS);
               while(1)
               {
                   if(isbutton2() == 0)
                       break;
               }
         }

        return;
    }

    if (x == 4)
        return;

    for (int i = x; i < 4; i++)
    {
        paht[i] = 1;
        DFS_r(i + 1, size, count + 1);
        paht[i] = 0;

        if(check1 == 1)return;

        if(isbutton2() == 0)
        {
            R_BSP_SoftwareDelay (20, BSP_DELAY_UNITS_MILLISECONDS);
            while(1)
            {
                if(isbutton2() == 0)
                    break;
            }
        }
    }

}


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */


    while(1){

        if(isbutton1() == 0 || check1 == 1){

            check1 = 0;
            check2 = 0;

            for (int i = 0; i < 5; i++)
                paht[i] = 0;


            for (int i = 1; i <= 4; i++)
            {

                if(isbutton2() == 0)
                {
                    R_BSP_SoftwareDelay (20, BSP_DELAY_UNITS_MILLISECONDS);
                    while(1)
                    {
                        if(isbutton2() == 0)
                            break;
                    }
                }


                if(isbutton1() == 0)
                    check1 = 1;

                if(check1 == 1)
                  break;

                DFS_r(0, i, 0);

            }

        }

        //R_IOPORT_PinWrite(&g_ioport_ctrl, LED1,1);
        //R_BSP_SoftwareDelay (200, BSP_DELAY_UNITS_MILLISECONDS);
        //R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, 0);
        //R_BSP_SoftwareDelay (200, BSP_DELAY_UNITS_MILLISECONDS);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {

    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}


